<?php

/**
 * BaseDepartment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $department_id
 * @property string $department
 * @property integer $faculty_id
 * @property Faculty $Faculty
 * @property Doctrine_Collection $Community
 * 
 * @method integer             getDepartmentId()  Returns the current record's "department_id" value
 * @method string              getDepartment()    Returns the current record's "department" value
 * @method integer             getFacultyId()     Returns the current record's "faculty_id" value
 * @method Faculty             getFaculty()       Returns the current record's "Faculty" value
 * @method Doctrine_Collection getCommunity()     Returns the current record's "Community" collection
 * @method Department          setDepartmentId()  Sets the current record's "department_id" value
 * @method Department          setDepartment()    Sets the current record's "department" value
 * @method Department          setFacultyId()     Sets the current record's "faculty_id" value
 * @method Department          setFaculty()       Sets the current record's "Faculty" value
 * @method Department          setCommunity()     Sets the current record's "Community" collection
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDepartment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('department');
        $this->hasColumn('department_id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('department', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 40,
             ));
        $this->hasColumn('faculty_id', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Faculty', array(
             'local' => 'faculty_id',
             'foreign' => 'faculty_id'));

        $this->hasMany('Community', array(
             'local' => 'department_id',
             'foreign' => 'department_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'department',
             ),
             ));
        $this->actAs($i18n0);
    }
}