<?php

/**
 * BaseOFields
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $did
 * @property integer $org_id
 * @property integer $biz_field_id
 * @property string $description
 * @property Organization $Organization
 * @property BizField $BizField
 * 
 * @method integer      getDid()          Returns the current record's "did" value
 * @method integer      getOrgId()        Returns the current record's "org_id" value
 * @method integer      getBizFieldId()   Returns the current record's "biz_field_id" value
 * @method string       getDescription()  Returns the current record's "description" value
 * @method Organization getOrganization() Returns the current record's "Organization" value
 * @method BizField     getBizField()     Returns the current record's "BizField" value
 * @method OFields      setDid()          Sets the current record's "did" value
 * @method OFields      setOrgId()        Sets the current record's "org_id" value
 * @method OFields      setBizFieldId()   Sets the current record's "biz_field_id" value
 * @method OFields      setDescription()  Sets the current record's "description" value
 * @method OFields      setOrganization() Sets the current record's "Organization" value
 * @method OFields      setBizField()     Sets the current record's "BizField" value
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOFields extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('o_fields');
        $this->hasColumn('did', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('org_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('biz_field_id', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('description', 'string', 35, array(
             'type' => 'string',
             'length' => 35,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organization', array(
             'local' => 'org_id',
             'foreign' => 'org_id',
             'onDelete' => 'Cascade'));

        $this->hasOne('BizField', array(
             'local' => 'biz_field_id',
             'foreign' => 'biz_field_id',
             'onDelete' => 'cascade'));
    }
}