<?php

/**
 * BaseJobPosition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $job_position_id
 * @property string $job_position
 * @property Doctrine_Collection $AOMap
 * 
 * @method integer             getJobPositionId()   Returns the current record's "job_position_id" value
 * @method string              getJobPosition()     Returns the current record's "job_position" value
 * @method Doctrine_Collection getAOMap()           Returns the current record's "AOMap" collection
 * @method JobPosition         setJobPositionId()   Sets the current record's "job_position_id" value
 * @method JobPosition         setJobPosition()     Sets the current record's "job_position" value
 * @method JobPosition         setAOMap()           Sets the current record's "AOMap" collection
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobPosition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('job_position');
        $this->hasColumn('job_position_id', 'integer', 1, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 1,
             ));
        $this->hasColumn('job_position', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AOMap', array(
             'local' => 'job_position_id',
             'foreign' => 'job_position_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'job_position',
             ),
             ));
        $this->actAs($i18n0);
    }
}