<?php

/**
 * BaseStrata
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $strata_id
 * @property string $strata
 * @property Doctrine_Collection $ADegrees
 * 
 * @method integer             getStrataId()  Returns the current record's "strata_id" value
 * @method string              getStrata()    Returns the current record's "strata" value
 * @method Doctrine_Collection getADegrees()  Returns the current record's "ADegrees" collection
 * @method Strata              setStrataId()  Sets the current record's "strata_id" value
 * @method Strata              setStrata()    Sets the current record's "strata" value
 * @method Strata              setADegrees()  Sets the current record's "ADegrees" collection
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStrata extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('strata');
        $this->hasColumn('strata_id', 'integer', 1, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 1,
             ));
        $this->hasColumn('strata', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ADegrees', array(
             'local' => 'strata_id',
             'foreign' => 'strata_id'));
    }
}