<?php

/**
 * BaseProvince
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $province_id
 * @property string $province
 * @property Doctrine_Collection $Address
 * 
 * @method integer             getProvinceId()  Returns the current record's "province_id" value
 * @method string              getProvince()    Returns the current record's "province" value
 * @method Doctrine_Collection getAddress()     Returns the current record's "Address" collection
 * @method Province            setProvinceId()  Sets the current record's "province_id" value
 * @method Province            setProvince()    Sets the current record's "province" value
 * @method Province            setAddress()     Sets the current record's "Address" collection
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProvince extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('province');
        $this->hasColumn('province_id', 'integer', 1, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 1,
             ));
        $this->hasColumn('province', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Address', array(
             'local' => 'province_id',
             'foreign' => 'province_id'));
    }
}