<?php

/**
 * BaseCountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $country_id
 * @property string $country
 * @property Doctrine_Collection $Address
 * 
 * @method integer             getCountryId()  Returns the current record's "country_id" value
 * @method string              getCountry()    Returns the current record's "country" value
 * @method Doctrine_Collection getAddress()    Returns the current record's "Address" collection
 * @method Country             setCountryId()  Sets the current record's "country_id" value
 * @method Country             setCountry()    Sets the current record's "country" value
 * @method Country             setAddress()    Sets the current record's "Address" collection
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCountry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('country');
        $this->hasColumn('country_id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 2,
             ));
        $this->hasColumn('country', 'string', 35, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 35,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Address', array(
             'local' => 'country_id',
             'foreign' => 'country_id'));
    }
}