<?php

/**
 * BaseOContacts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Organization $Organization
 * 
 * @method Organization getOrganization() Returns the current record's "Organization" value
 * @method OContacts    setOrganization() Sets the current record's "Organization" value
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOContacts extends Contacts
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organization', array(
             'local' => 'lid',
             'foreign' => 'org_id',
             'onDelete' => 'CASCADE'));
    }
}