<?php

/**
 * BaseBizField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $biz_field_id
 * @property string $biz_field
 * @property clob $description
 * @property Doctrine_Collection $OFields
 * 
 * @method integer             getBizFieldId()   Returns the current record's "biz_field_id" value
 * @method string              getBizField()     Returns the current record's "biz_field" value
 * @method clob                getDescription()  Returns the current record's "description" value
 * @method Doctrine_Collection getOFields()      Returns the current record's "OFields" collection
 * @method BizField            setBizFieldId()   Sets the current record's "biz_field_id" value
 * @method BizField            setBizField()     Sets the current record's "biz_field" value
 * @method BizField            setDescription()  Sets the current record's "description" value
 * @method BizField            setOFields()      Sets the current record's "OFields" collection
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBizField extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('biz_field');
        $this->hasColumn('biz_field_id', 'integer', 1, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 1,
             ));
        $this->hasColumn('biz_field', 'string', 35, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 35,
             ));
        $this->hasColumn('description', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('OFields', array(
             'local' => 'biz_field_id',
             'foreign' => 'biz_field_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'biz_field',
             ),
             ));
        $this->actAs($i18n0);
    }
}