<?php

/**
 * BaseACommunities
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $did
 * @property integer $aid
 * @property integer $cid
 * @property integer $class_year
 * @property string $class_sub
 * @property string $community
 * @property integer $department_id
 * @property integer $faculty_id
 * @property integer $program_id
 * @property Alumni $Alumni
 * @property Community $Community
 * @property Department $Department
 * @property Faculty $Faculty
 * @property Program $Program
 * 
 * @method integer      getDid()           Returns the current record's "did" value
 * @method integer      getAid()           Returns the current record's "aid" value
 * @method integer      getCid()           Returns the current record's "cid" value
 * @method integer      getClassYear()     Returns the current record's "class_year" value
 * @method string       getClassSub()      Returns the current record's "class_sub" value
 * @method string       getCommunity()     Returns the current record's "community" value
 * @method integer      getDepartmentId()  Returns the current record's "department_id" value
 * @method integer      getFacultyId()     Returns the current record's "faculty_id" value
 * @method integer      getProgramId()     Returns the current record's "program_id" value
 * @method Alumni       getAlumni()        Returns the current record's "Alumni" value
 * @method Community    getCommunity()     Returns the current record's "Community" value
 * @method Department   getDepartment()    Returns the current record's "Department" value
 * @method Faculty      getFaculty()       Returns the current record's "Faculty" value
 * @method Program      getProgram()       Returns the current record's "Program" value
 * @method ACommunities setDid()           Sets the current record's "did" value
 * @method ACommunities setAid()           Sets the current record's "aid" value
 * @method ACommunities setCid()           Sets the current record's "cid" value
 * @method ACommunities setClassYear()     Sets the current record's "class_year" value
 * @method ACommunities setClassSub()      Sets the current record's "class_sub" value
 * @method ACommunities setCommunity()     Sets the current record's "community" value
 * @method ACommunities setDepartmentId()  Sets the current record's "department_id" value
 * @method ACommunities setFacultyId()     Sets the current record's "faculty_id" value
 * @method ACommunities setProgramId()     Sets the current record's "program_id" value
 * @method ACommunities setAlumni()        Sets the current record's "Alumni" value
 * @method ACommunities setCommunity()     Sets the current record's "Community" value
 * @method ACommunities setDepartment()    Sets the current record's "Department" value
 * @method ACommunities setFaculty()       Sets the current record's "Faculty" value
 * @method ACommunities setProgram()       Sets the current record's "Program" value
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseACommunities extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('a_communities');
        $this->hasColumn('did', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('aid', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('cid', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('class_year', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'range' => 
             array(
              0 => 1964,
              1 => 2015,
             ),
             'length' => 2,
             ));
        $this->hasColumn('class_sub', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('community', 'string', 70, array(
             'type' => 'string',
             'length' => 70,
             ));
        $this->hasColumn('department_id', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('faculty_id', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('program_id', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));


        $this->setAttribute(Doctrine_Core::ATTR_VALIDATE, true);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Alumni', array(
             'local' => 'aid',
             'foreign' => 'aid',
             'onDelete' => 'Cascade'));

        $this->hasOne('Community', array(
             'local' => 'cid',
             'foreign' => 'cid',
             'onDelete' => 'Cascade'));

        $this->hasOne('Department', array(
             'local' => 'department_id',
             'foreign' => 'department_id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Faculty', array(
             'local' => 'faculty_id',
             'foreign' => 'faculty_id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Program', array(
             'local' => 'program_id',
             'foreign' => 'program_id',
             'onDelete' => 'SET NULL'));
    }
}