<?php

/**
 * BaseProgram
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $program_id
 * @property string $program
 * @property Doctrine_Collection $Community
 * 
 * @method integer             getProgramId()  Returns the current record's "program_id" value
 * @method string              getProgram()    Returns the current record's "program" value
 * @method Doctrine_Collection getCommunity()  Returns the current record's "Community" collection
 * @method Program             setProgramId()  Sets the current record's "program_id" value
 * @method Program             setProgram()    Sets the current record's "program" value
 * @method Program             setCommunity()  Sets the current record's "Community" collection
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProgram extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('program');
        $this->hasColumn('program_id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('program', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Community', array(
             'local' => 'program_id',
             'foreign' => 'program_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'program',
             ),
             ));
        $this->actAs($i18n0);
    }
}