<?php

/**
 * BaseCompetency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $competency_id
 * @property string $competency
 * @property clob $memo
 * @property Doctrine_Collection $ACompetencies
 * 
 * @method integer             getCompetencyId()  Returns the current record's "competency_id" value
 * @method string              getCompetency()    Returns the current record's "competency" value
 * @method clob                getMemo()          Returns the current record's "memo" value
 * @method Doctrine_Collection getACompetencies() Returns the current record's "ACompetencies" collection
 * @method Competency          setCompetencyId()  Sets the current record's "competency_id" value
 * @method Competency          setCompetency()    Sets the current record's "competency" value
 * @method Competency          setMemo()          Sets the current record's "memo" value
 * @method Competency          setACompetencies() Sets the current record's "ACompetencies" collection
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompetency extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('competency');
        $this->hasColumn('competency_id', 'integer', 1, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 1,
             ));
        $this->hasColumn('competency', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 30,
             ));
        $this->hasColumn('memo', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ACompetencies', array(
             'local' => 'competency_id',
             'foreign' => 'competency_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'competency',
             ),
             ));
        $this->actAs($i18n0);
    }
}