<?php

/**
 * BaseMContacts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property AOMap $AOMap
 * 
 * @method AOMap     getAOMap() Returns the current record's "AOMap" value
 * @method MContacts setAOMap() Sets the current record's "AOMap" value
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMContacts extends Contacts
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AOMap', array(
             'local' => 'lid',
             'foreign' => 'mid',
             'onDelete' => 'CASCADE'));
    }
}