<?php

/**
 * BaseOrganization
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $org_id
 * @property string $name
 * @property string $prefix
 * @property string $suffix
 * @property clob $note
 * @property string $product
 * @property string $fullname
 * @property Doctrine_Collection $Organization
 * 
 * @method integer             getOrgId()        Returns the current record's "org_id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getPrefix()       Returns the current record's "prefix" value
 * @method string              getSuffix()       Returns the current record's "suffix" value
 * @method clob                getNote()         Returns the current record's "note" value
 * @method string              getProduct()      Returns the current record's "product" value
 * @method string              getFullname()     Returns the current record's "fullname" value
 * @method Doctrine_Collection getOrganization() Returns the current record's "Organization" collection
 * @method Organization        setOrgId()        Sets the current record's "org_id" value
 * @method Organization        setName()         Sets the current record's "name" value
 * @method Organization        setPrefix()       Sets the current record's "prefix" value
 * @method Organization        setSuffix()       Sets the current record's "suffix" value
 * @method Organization        setNote()         Sets the current record's "note" value
 * @method Organization        setProduct()      Sets the current record's "product" value
 * @method Organization        setFullname()     Sets the current record's "fullname" value
 * @method Organization        setOrganization() Sets the current record's "Organization" collection
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrganization extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('organization');
        $this->hasColumn('oid as org_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('prefix', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('suffix', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('note', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('product', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('fullname', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AOMap as Organization', array(
             'local' => 'org_id',
             'foreign' => 'org_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $this->actAs($timestampable0);
        $this->actAs($nestedset0);
    }
}