<?php

/**
 * BaseContactType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ct_id
 * @property string $contact_type
 * @property Doctrine_Collection $Contacts
 * 
 * @method integer             getCtId()         Returns the current record's "ct_id" value
 * @method string              getContactType()  Returns the current record's "contact_type" value
 * @method Doctrine_Collection getContacts()     Returns the current record's "Contacts" collection
 * @method ContactType         setCtId()         Sets the current record's "ct_id" value
 * @method ContactType         setContactType()  Sets the current record's "contact_type" value
 * @method ContactType         setContacts()     Sets the current record's "Contacts" collection
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContactType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contact_type');
        $this->hasColumn('ct_id', 'integer', 1, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 1,
             ));
        $this->hasColumn('contact_type', 'string', 25, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Contacts', array(
             'local' => 'ct_id',
             'foreign' => 'ct_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'contact_type',
             ),
             ));
        $this->actAs($i18n0);
    }
}