<?php

/**
 * BaseContacts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $did
 * @property integer $lid
 * @property char $link_type
 * @property integer $ct_id
 * @property string $contact
 * @property ContactType $ContactType
 * 
 * @method integer     getDid()         Returns the current record's "did" value
 * @method integer     getLid()         Returns the current record's "lid" value
 * @method char        getLinkType()    Returns the current record's "link_type" value
 * @method integer     getCtId()        Returns the current record's "ct_id" value
 * @method string      getContact()     Returns the current record's "contact" value
 * @method ContactType getContactType() Returns the current record's "ContactType" value
 * @method Contacts    setDid()         Sets the current record's "did" value
 * @method Contacts    setLid()         Sets the current record's "lid" value
 * @method Contacts    setLinkType()    Sets the current record's "link_type" value
 * @method Contacts    setCtId()        Sets the current record's "ct_id" value
 * @method Contacts    setContact()     Sets the current record's "contact" value
 * @method Contacts    setContactType() Sets the current record's "ContactType" value
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContacts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contacts');
        $this->hasColumn('did', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('lid', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('link_type', 'char', 1, array(
             'type' => 'char',
             'length' => 1,
             ));
        $this->hasColumn('ct_id', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('contact', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));


        $this->setAttribute(Doctrine_Core::ATTR_EXPORT, 'table');

        $this->setSubClasses(array(
             'AContacts' => 
             array(
              'link_type' => 'A',
             ),
             'OContacts' => 
             array(
              'link_type' => 'O',
             ),
             'MContacts' => 
             array(
              'link_type' => 'M',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ContactType', array(
             'local' => 'ct_id',
             'foreign' => 'ct_id',
             'onDelete' => 'SET NULL'));
    }
}