<?php

/**
 * BaseFaculty
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $faculty_id
 * @property string $faculty
 * @property Doctrine_Collection $Department
 * @property Doctrine_Collection $Community
 * 
 * @method integer             getFacultyId()  Returns the current record's "faculty_id" value
 * @method string              getFaculty()    Returns the current record's "faculty" value
 * @method Doctrine_Collection getDepartment() Returns the current record's "Department" collection
 * @method Doctrine_Collection getCommunity()  Returns the current record's "Community" collection
 * @method Faculty             setFacultyId()  Sets the current record's "faculty_id" value
 * @method Faculty             setFaculty()    Sets the current record's "faculty" value
 * @method Faculty             setDepartment() Sets the current record's "Department" collection
 * @method Faculty             setCommunity()  Sets the current record's "Community" collection
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFaculty extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faculty');
        $this->hasColumn('faculty_id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('faculty', 'string', 35, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 35,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Department', array(
             'local' => 'faculty_id',
             'foreign' => 'faculty_id'));

        $this->hasMany('Community', array(
             'local' => 'faculty_id',
             'foreign' => 'faculty_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'faculty',
             ),
             ));
        $this->actAs($i18n0);
    }
}