<?php

/**
 * BaseAlumni
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $aid
 * @property string $name
 * @property string $prefix
 * @property string $suffix
 * @property clob $note
 * @property char $gender
 * @property string $birthplace
 * @property date $birthdate
 * @property integer $religion_id
 * @property string $fullname
 * @property Religion $Religion
 * @property Doctrine_Collection $ACommunities
 * @property Doctrine_Collection $ACompetencies
 * @property Doctrine_Collection $ACertifications
 * 
 * @method integer             getAid()             Returns the current record's "aid" value
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getPrefix()          Returns the current record's "prefix" value
 * @method string              getSuffix()          Returns the current record's "suffix" value
 * @method clob                getNote()            Returns the current record's "note" value
 * @method char                getGender()          Returns the current record's "gender" value
 * @method string              getBirthplace()      Returns the current record's "birthplace" value
 * @method date                getBirthdate()       Returns the current record's "birthdate" value
 * @method integer             getReligionId()      Returns the current record's "religion_id" value
 * @method string              getFullname()        Returns the current record's "fullname" value
 * @method Religion            getReligion()        Returns the current record's "Religion" value
 * @method Doctrine_Collection getACommunities()    Returns the current record's "ACommunities" collection
 * @method Doctrine_Collection getACompetencies()   Returns the current record's "ACompetencies" collection
 * @method Doctrine_Collection getACertifications() Returns the current record's "ACertifications" collection
 * @method Alumni              setAid()             Sets the current record's "aid" value
 * @method Alumni              setName()            Sets the current record's "name" value
 * @method Alumni              setPrefix()          Sets the current record's "prefix" value
 * @method Alumni              setSuffix()          Sets the current record's "suffix" value
 * @method Alumni              setNote()            Sets the current record's "note" value
 * @method Alumni              setGender()          Sets the current record's "gender" value
 * @method Alumni              setBirthplace()      Sets the current record's "birthplace" value
 * @method Alumni              setBirthdate()       Sets the current record's "birthdate" value
 * @method Alumni              setReligionId()      Sets the current record's "religion_id" value
 * @method Alumni              setFullname()        Sets the current record's "fullname" value
 * @method Alumni              setReligion()        Sets the current record's "Religion" value
 * @method Alumni              setACommunities()    Sets the current record's "ACommunities" collection
 * @method Alumni              setACompetencies()   Sets the current record's "ACompetencies" collection
 * @method Alumni              setACertifications() Sets the current record's "ACertifications" collection
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlumni extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('alumni');
        $this->hasColumn('aid', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('prefix', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('suffix', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('note', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('gender', 'char', 1, array(
             'type' => 'char',
             'length' => 1,
             ));
        $this->hasColumn('birthplace', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('birthdate', 'date', null, array(
             'type' => 'date',
             'past' => true,
             ));
        $this->hasColumn('religion_id', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('fullname', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Religion', array(
             'local' => 'religion_id',
             'foreign' => 'religion_id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('ACommunities', array(
             'local' => 'aid',
             'foreign' => 'aid'));

        $this->hasMany('ACompetencies', array(
             'local' => 'aid',
             'foreign' => 'aid'));

        $this->hasMany('ACertifications', array(
             'local' => 'aid',
             'foreign' => 'aid'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}