<?php

/**
 * BaseACompetencies
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $did
 * @property integer $aid
 * @property integer $competency_id
 * @property string $description
 * @property Alumni $Alumni
 * @property Competency $Competency
 * 
 * @method integer       getDid()           Returns the current record's "did" value
 * @method integer       getAid()           Returns the current record's "aid" value
 * @method integer       getCompetencyId()  Returns the current record's "competency_id" value
 * @method string        getDescription()   Returns the current record's "description" value
 * @method Alumni        getAlumni()        Returns the current record's "Alumni" value
 * @method Competency    getCompetency()    Returns the current record's "Competency" value
 * @method ACompetencies setDid()           Sets the current record's "did" value
 * @method ACompetencies setAid()           Sets the current record's "aid" value
 * @method ACompetencies setCompetencyId()  Sets the current record's "competency_id" value
 * @method ACompetencies setDescription()   Sets the current record's "description" value
 * @method ACompetencies setAlumni()        Sets the current record's "Alumni" value
 * @method ACompetencies setCompetency()    Sets the current record's "Competency" value
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseACompetencies extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('a_competencies');
        $this->hasColumn('did', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('aid', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('competency_id', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('description', 'string', 35, array(
             'type' => 'string',
             'length' => 35,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Alumni', array(
             'local' => 'aid',
             'foreign' => 'aid',
             'onDelete' => 'Cascade'));

        $this->hasOne('Competency', array(
             'local' => 'competency_id',
             'foreign' => 'competency_id',
             'onDelete' => 'Cascade'));
    }
}