<?php

/**
 * BaseJobType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $job_type_id
 * @property string $job_type
 * @property Doctrine_Collection $AOMap
 * 
 * @method integer             getJobTypeId()   Returns the current record's "job_type_id" value
 * @method string              getJobType()     Returns the current record's "job_type" value
 * @method Doctrine_Collection getAOMap()       Returns the current record's "AOMap" collection
 * @method JobType             setJobTypeId()   Sets the current record's "job_type_id" value
 * @method JobType             setJobType()     Sets the current record's "job_type" value
 * @method JobType             setAOMap()       Sets the current record's "AOMap" collection
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('job_type');
        $this->hasColumn('job_type_id', 'integer', 1, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 1,
             ));
        $this->hasColumn('job_type', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AOMap', array(
             'local' => 'job_type_id',
             'foreign' => 'job_type_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'job_type',
             ),
             ));
        $this->actAs($i18n0);
    }
}