<?php

/**
 * BaseDistrict
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $district_id
 * @property string $district
 * @property integer $province_id
 * @property Province $Province
 * @property Doctrine_Collection $Address
 * 
 * @method integer             getDistrictId()  Returns the current record's "district_id" value
 * @method string              getDistrict()    Returns the current record's "district" value
 * @method integer             getProvinceId()  Returns the current record's "province_id" value
 * @method Province            getProvince()    Returns the current record's "Province" value
 * @method Doctrine_Collection getAddress()     Returns the current record's "Address" collection
 * @method District            setDistrictId()  Sets the current record's "district_id" value
 * @method District            setDistrict()    Sets the current record's "district" value
 * @method District            setProvinceId()  Sets the current record's "province_id" value
 * @method District            setProvince()    Sets the current record's "Province" value
 * @method District            setAddress()     Sets the current record's "Address" collection
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDistrict extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('district');
        $this->hasColumn('district_id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 2,
             ));
        $this->hasColumn('district', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 30,
             ));
        $this->hasColumn('province_id', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Province', array(
             'local' => 'province_id',
             'foreign' => 'province_id'));

        $this->hasMany('Address', array(
             'local' => 'district_id',
             'foreign' => 'district_id'));
    }
}