<?php

/**
 * BaseADegrees
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $did
 * @property integer $aid
 * @property integer $strata_id
 * @property integer $admitted
 * @property integer $graduated
 * @property string $degree
 * @property string $institution
 * @property string $major
 * @property string $minor
 * @property string $concentration
 * @property Alumni $Alumni
 * @property Strata $Strata
 * 
 * @method integer  getDid()           Returns the current record's "did" value
 * @method integer  getAid()           Returns the current record's "aid" value
 * @method integer  getStrataId()      Returns the current record's "strata_id" value
 * @method integer  getAdmitted()      Returns the current record's "admitted" value
 * @method integer  getGraduated()     Returns the current record's "graduated" value
 * @method string   getDegree()        Returns the current record's "degree" value
 * @method string   getInstitution()   Returns the current record's "institution" value
 * @method string   getMajor()         Returns the current record's "major" value
 * @method string   getMinor()         Returns the current record's "minor" value
 * @method string   getConcentration() Returns the current record's "concentration" value
 * @method Alumni   getAlumni()        Returns the current record's "Alumni" value
 * @method Strata   getStrata()        Returns the current record's "Strata" value
 * @method ADegrees setDid()           Sets the current record's "did" value
 * @method ADegrees setAid()           Sets the current record's "aid" value
 * @method ADegrees setStrataId()      Sets the current record's "strata_id" value
 * @method ADegrees setAdmitted()      Sets the current record's "admitted" value
 * @method ADegrees setGraduated()     Sets the current record's "graduated" value
 * @method ADegrees setDegree()        Sets the current record's "degree" value
 * @method ADegrees setInstitution()   Sets the current record's "institution" value
 * @method ADegrees setMajor()         Sets the current record's "major" value
 * @method ADegrees setMinor()         Sets the current record's "minor" value
 * @method ADegrees setConcentration() Sets the current record's "concentration" value
 * @method ADegrees setAlumni()        Sets the current record's "Alumni" value
 * @method ADegrees setStrata()        Sets the current record's "Strata" value
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseADegrees extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('a_degrees');
        $this->hasColumn('did', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('aid', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('strata_id', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('admitted', 'integer', 2, array(
             'type' => 'integer',
             'range' => 
             array(
              0 => 1964,
              1 => 2015,
             ),
             'length' => 2,
             ));
        $this->hasColumn('graduated', 'integer', 2, array(
             'type' => 'integer',
             'range' => 
             array(
              0 => 1964,
              1 => 2015,
             ),
             'length' => 2,
             ));
        $this->hasColumn('degree', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('institution', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 40,
             ));
        $this->hasColumn('major', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('minor', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('concentration', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));


        $this->setAttribute(Doctrine_Core::ATTR_VALIDATE, true);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Alumni', array(
             'local' => 'aid',
             'foreign' => 'aid',
             'onDelete' => 'Cascade'));

        $this->hasOne('Strata', array(
             'local' => 'strata_id',
             'foreign' => 'strata_id',
             'onDelete' => 'SET NULL'));
    }
}