<?php

/**
 * AAddressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AAddressTable extends AddressTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AAddressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AAddress');
    }
}