<?php

/**
 * AAddress
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi
 * @version    1.0
 */
class AAddress extends BaseAAddress
{     
}

$aAddressTable = Doctrine_Core::getTable('AAddress');
$aAddressTable->addRecordListener(new AddressHydrationListener());
