<?php

/**
 * ACertificationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ACertificationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ACertificationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ACertifications');
    }
}
