<?php

/**
 * ACommunities
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi
 * @version    1.0
 */
class ACommunities extends BaseACommunities
{
/*  Sample!	
    protected function validate()
    {
        if ($this->class_year == 1993) {
            // syntax: add(<fieldName>, <error code/identifier>)
            $errorStack = $this->getErrorStack();
            $errorStack->add('class_year', 'You cannot use this 1993 year!');
        }
    }*/
    
	public function __toString()
	{
		return sprintf('%s', $this->get('community'));
	}
    
	public function getRefText()
	{
		$text = $this->getCommunity();
		$year = $this->getClassYear();
		$sub = $this->getClassSub();
		if (!empty($year))		{ $text .=  ' - '.$year; }
		if (!empty($sub))	{ $text .=  ' ('.$sub.')'; }

		return $text;
	}
	
	public function getRefLink()
	{
		$dept = $this->get('department_id');  
		$prog = $this->get('program_id');  
		$fcly = $this->get('faculty_id');  
		$year = $this->get('class_year');  
	
		$url_params = array();
		if ($dept) $url_params[] = 'dept='.$dept;
		if ($prog) $url_params[] = 'prog='.$prog;
		if ($fcly) $url_params[] = 'fcly='.$fcly;
		if ($year) $url_params[] = 'year='.$year;
	
		$url_all_param = implode('&', $url_params);
	
		return url_for('acommunities/filter?'.$url_all_param);
	}
	
}

// Port from firebird trigger
// CREATE TRIGGER SET_CommunityAlias FOR ACommunities
class ACommunitiesHydrationListener extends Doctrine_Record_Listener
{
     public function preSave(Doctrine_Event $event)
    {
        $invoker = $event->getInvoker();		
		$cid = (int) $invoker->cid;
		
		$q = Doctrine_Query::create()
			->from('Community')
			->where('cid = '.$cid)
			->limit(1);
		$result = $q->execute();
		$rows = $result->toArray();
		$comy = $rows[0];
		
        $invoker->program_id	= $comy['program_id'];
        $invoker->department_id	= $comy['department_id'];
        $invoker->faculty_id	= $comy['faculty_id']; 
        
        $year = $invoker->class_year;
        if (empty($comy['brief']))
			$alias =  $comy['community'];
		else	
		{				
			$alias = $comy['brief'];
			$year = substr($year, 2, 2);
		}
        
        
        if	(!empty($invoker->class_sub))
			$year = $year.' ('.$invoker->class_sub.')';
			
		if	(!empty($year)	)
			$alias = $alias.' - '.$year;
        
        $invoker->community = $alias;        
        // echo '++ '.$alias."\n";
    }

}

$aCommunitiesTable = Doctrine_Core::getTable('ACommunities');
$aCommunitiesTable->addRecordListener(new ACommunitiesHydrationListener());


