<?php

/**
 * ACompetenciesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ACompetenciesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ACompetenciesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ACompetencies');
    }
}