<?php

/**
 * ACommunitiesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ACommunitiesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ACommunitiesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ACommunities');
    }
}
