<?php

/**
 * AContactsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AContactsTable extends ContactsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AContactsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AContacts');
    }
}