<?php

/**
 * Address
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi
 * @version    1.0
 */
class Address extends BaseAddress
{
}

class AddressHydrationListener extends Doctrine_Record_Listener
{
    public function preSave(Doctrine_Event $event)
    {
		$address = $region = array();
        $row = $event->getInvoker();

		// address part
        if (!empty($row->building))	$address[] = $row->building;
		if (!empty($row->street))	$address[] = $row->street;
		if (!empty($row->area))		$address[] = $row->area;
		
		$row->address = implode(', ', $address);
		
		// region part
		if ($row->district_id)
			$region[] = Doctrine_Core::getTable('District')
				->find($row->district_id)->get('district');

		if ($row->province_id)
			$region[] = Doctrine_Core::getTable('Province')
				->find($row->province_id)->get('province');
		
		if ($row->country_id)
			$region[] = Doctrine_Core::getTable('Country')
				->find($row->country_id)->get('country');
		
		if ($row->postal_code)
			$region[] = $row->postal_code;

		$row->region = implode(', ', $region);
    }
}
