<?php

/**
 * AExperiencesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AExperiencesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AExperiencesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AExperiences');
    }
}