<?php

/**
 * AlumniTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlumniTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlumniTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Alumni');
    }
    
	public function getLastUpdate()	
	{
		$rows = $this
			->createQuery('a')
			->select('max(a.updated_at) as last_update')
			->execute();
			
		return $rows->getFirst()->get('last_update');
    }
    
	public function getLastUpdateForAtom()	
	{
		$rows = $this
			->createQuery('a')
			->select('max(a.updated_at) as last_update')
			->execute();
			
		$text = $rows
			->getFirst()
			->getDateTimeObject('updated_at')
			->format('U');	
	
		return $text;
    }
    
    public function getAlumniForAtom()
	{
		$rows = $this
			->createQuery('a')
			->select('a.aid, a.fullname, ac.*')
			->leftJoin('a.ACommunities ac')
			->orderBy('a.updated_at desc')
			->limit(10)
			->execute();

		return $rows;	
	}
}
