<?php

/**
 * Alumni
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi
 * @version    1.0
 */
class Alumni extends BaseAlumni
{
	static protected $gender_choices = array(
		null => 'Unknown',
		'M' => 'Male',
		'F'     => 'Female'
	);
	 
	static public function getGenderChoices()
	{
		return self::$gender_choices;
	}
  
	public function getGenderText()
	{
		return $this->gender_choices[ $this->get('gender') ];
	}

}

class AlumniHydrationListener extends Doctrine_Record_Listener
{
    public function preSave(Doctrine_Event $event)
    {
        $invoker = $event->getInvoker();
        $prefix = $invoker->prefix;
        $suffix = $invoker->suffix;
        $name = $invoker->name;
        
        if(!empty($prefix)) $name = $prefix.' '.$name;
        if(!empty($suffix)) $name = $name.', '.$suffix;

		$invoker->fullname = $name;        
    }

}

$alumniTable = Doctrine_Core::getTable('Alumni');
$alumniTable->addRecordListener(new AlumniHydrationListener());

