<?php

/**
 * AOMapTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AOMapTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AOMapTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AOMap');
    }
}