<?php

/**
 * BizField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi <epsi.rns@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BizField extends BaseBizField
{
  public function __toString()
  {
    return sprintf('%s', $this->get('biz_field'));
  }
}
