<?php

/**
 * BizFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BizFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BizFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BizField');
    }
    
	public function retrieveBackendBizField(Doctrine_Query $q)
	{
		$r = $q->getRootAlias(); 
		$q->leftJoin($r.'.Translation t');
		return $q;
	}
}
