<?php

/**
 * CommunityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommunityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommunityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Community');
    }
    
	public function retrieveBackendCommunity(Doctrine_Query $q)
	{
		$r = $q->getRootAlias(); 
		$q	->leftJoin($r.'.Faculty f') 
			->leftJoin($r.'.Department d') 
			->leftJoin($r.'.Program p'); 
		return $q;
	}
}
