<?php

/**
 * Community
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi
 * @version    1.0
 */
class Community extends BaseCommunity
{
	static protected $type_choices = array(
		1 => 'Academic Formal',
		2 => 'Student Club'
	);
	
	public function __toString()
	{
		return sprintf('%s', $this->get('community'));
	}
	
	static public function getTypeIdChoices()
	{
		return self::$type_choices;
	}
  
	public function getTypeIdText()
	{
		return $this->type_choices[ $this->get('type_id') ];
	}	
}
