<?php

/**
 * CompetencyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompetencyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompetencyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Competency');
    }
    
	public function retrieveBackendCompetency(Doctrine_Query $q)
	{
		$r = $q->getRootAlias(); 
		$q->leftJoin($r.'.Translation t');
		return $q;
	}
}
