<?php

/**
 * ContactsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contacts');
    }
}