<?php

/**
 * ContactTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactType');
    }
}