<?php

/**
 * DepartmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DepartmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DepartmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Department');
    }
    
	public function retrieveBackendDepartment(Doctrine_Query $q)
	{
		$r = $q->getRootAlias(); 
		$q
			->where($r.'.department_id > 0')
			->leftJoin($r.'.Translation td');			
		$q
			->leftJoin($r.'.Faculty f')
			->leftJoin('f.Translation tf');
		return $q;
	}
}
