<?php

/**
 * District
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi
 * @version    1.0
 */
class District extends BaseDistrict
{
	public function __toString()
	{
		return sprintf('%s', $this->get('district'));
	}
	
	public function preDelete($event)
	{
		$id = $this->get('district_id');
		if ($id<=0)
			$event->skipOperation();
	}
}

