<?php

/**
 * DistrictTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DistrictTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DistrictTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('District');
    }
    
	public function retrieveBackendDistrict(Doctrine_Query $q)
	{
		$r = $q->getRootAlias(); 
		$q->leftJoin($r.'.Province p'); 
		$q->where($r.'.district_id > 0');
		return $q;
	}
}
