<?php

/**
 * FacultyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacultyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FacultyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Faculty');
    }
    
	public function retrieveBackendFaculty(Doctrine_Query $q)
	{
		$rootAlias = $q->getRootAlias(); 
		$q->where($r.'.faculty_id > 0');
		return $q;
	}
}
