<?php

/**
 * Faculty
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi
 * @version    1.0
 */
class Faculty extends BaseFaculty
{
	public function __toString()
	{
		return sprintf('%s', $this->get('faculty'));
	}
	
	public function getDepartments($lang)
	{
		$q = Doctrine_Core::getTable('Department')
			->createQuery('d')
			->leftJoin('d.Translation t')
			->where('t.lang = ?', $lang)  
			->where('d.faculty_id = ?', $this->getFacultyId());
 
		return $q->execute();
	}
}
