<?php

/**
 * JobPositionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobPositionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobPositionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobPosition');
    }
}