<?php

/**
 * MAddressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MAddressTable extends AddressTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MAddressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MAddress');
    }
}