<?php

/**
 * MContactsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MContactsTable extends ContactsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MContactsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MContacts');
    }
}