<?php

/**
 * OAddressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OAddressTable extends AddressTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OAddressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OAddress');
    }
}