<?php

/**
 * OAddress
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi
 * @version    1.0
 */
class OAddress extends BaseOAddress
{
}

$oAddressTable = Doctrine_Core::getTable('OAddress');
$oAddressTable->addRecordListener(new AddressHydrationListener());
