<?php

/**
 * OContactsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OContactsTable extends ContactsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OContactsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OContacts');
    }
}