<?php

/**
 * OFieldsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OFieldsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OFieldsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OFields');
    }
}