<?php

/**
 * Organization
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    alumni
 * @subpackage model
 * @author     E.R. Nurwijayadi
 * @version    1.0
 */
class Organization extends BaseOrganization
{
}

class OrgHydrationListener extends Doctrine_Record_Listener
{
    public function preSave(Doctrine_Event $event)
    {
        $invoker = $event->getInvoker();
        $prefix = $invoker->prefix;
        $suffix = $invoker->suffix;
        $name = $invoker->name;
        
        if(!empty($prefix)) $name = $prefix.' '.$name;
        if(!empty($suffix)) $name = $name.', '.$suffix;

		$invoker->fullname = $name;        
    }

}

$orgTable = Doctrine_Core::getTable('Organization');
$orgTable->addRecordListener(new OrgHydrationListener());
