<?php

/**
 * ProvinceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProvinceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProvinceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Province');
    }
    
	public function retrieveBackendProvince(Doctrine_Query $q)
	{
		$r = $q->getRootAlias(); 
		$q->where($r.'.province_id > 0');
		return $q;
	}
}
