<?php

/**
 * ReligionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReligionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReligionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Religion');
    }
}