<?php

/**
 * StrataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StrataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StrataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Strata');
    }
}
