all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=sf_alumni'
      username: root
      password: 

#test:
#  doctrine:
#    class: sfDoctrineDatabase
#    param:
#      dsn: 'sqlite:////home/epsi/web.dev/AlumniBook.sqlite?mode=0666'

#-- deprecated firebird   
#      dsn: 'firebird://SYSDBA:masterkey@localhost/home/epsi/update/AlumniBook.fdb'
#      dsn: 'firebird:dbname=localhost:/home/epsi/update/AlumniBook.fdb'
#      username: SYSDBA
#      password: masterkey
