generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Program
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          program
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        table_method: retrieveBackendProgram
        title: Manage University Program
        sort: [program_id, asc]
        display: [=program]
        batch_actions: {}        
      filter:  ~
      form:    ~
      edit:
        title: Editing University Program "<i>%%program%%</i>"
      new:
        title: New Univeristy Program

      fields:
        faculty:
          help: A university program name
